# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a6abc49f3e92206a8274b7beecdbd6d18e6954f2b61cd99328af3603e7fc8822268a8349aebbccb6a8361704f0d2332f4696f7b14fcd04002203d500eadedb12

test:
  secret_key_base: f5cc90ac6ceca966a8e3b930cc478268eb8ff2285352add748fcc7f92768cac9dc137dd64d8811621e69cd65d8d9910376c6a4e3277577297615bed7965f663e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
